name: Common jobs workflow

on:
  workflow_call:
    outputs:
      strategy:
        description: "Matrix strategy for generating jobs"
        value: ${{ jobs.generate-jobs.outputs.strategy }}
    
defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:

  verify-templates:
    name: Check For Uncomitted Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download libraries
        run: ./download-libs.sh
      - name: Apply Templates
        run: ./apply-templates.sh
      - name: Check Git Status
        run: |
          status="$(git status --short)"
          [ -z "$status" ]

  generate-jobs:
    name: Generate Jobs
    needs: verify-templates
    runs-on: ubuntu-latest
    outputs:
      strategy: ${{ steps.generate-jobs.outputs.strategy }}
    steps:
      - uses: actions/checkout@v3
      - name: Download libraries
        run: ./download-libs.sh
      - id: generate-jobs
        name: Generate Jobs
        run: |
          strategy="$(./generate-jobs.sh)"
          echo "strategy=$strategy" >> "$GITHUB_OUTPUT"
          jq . <<<"$strategy" # sanity check / debugging aid
