name: Main branch workflow

on:
  push:
    branches:
      - 'main'

jobs:

  common:
    uses: ./.github/workflows/common.yml

  test:
    needs: common
    strategy: ${{ fromJson(needs.common.outputs.strategy) }}
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    environment: publishing
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.dir }}
          platforms: ${{ matrix.arches }}
          push: true
          tags: ${{ matrix.tags }}
