name: PR workflow

on:
  pull_request:

jobs:

  common:
    uses: ./.github/workflows/common.yml

  test:
    needs: common
    strategy: ${{ fromJson(needs.common.outputs.strategy) }}
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.dir }}
          tags: ${{ matrix.tags }}
